export enum VoiceState {
  VOICE_UNAVAILABLE = "VOICE_UNAVAILABLE",
  AMBIENT_UNAVAILABLE = "AMBIENT_UNAVAILABLE",
  MIC_DENIED = "MIC_DENIED",
  AMBIENT_LISTENING = "AMBIENT_LISTENING",
  GREETING_DETECTED = "GREETING_DETECTED",
  ACKNOWLEDGING = "ACKNOWLEDGING",
  ACTIVE_LISTENING = "ACTIVE_LISTENING",
  PROCESSING = "PROCESSING",
  RESPONDING = "RESPONDING",
}

export const GREETINGS = {
  PRIMARY: ["hey codesight", "codesight"],
  SECONDARY: ["good morning", "hello codesight", "you there"],
};

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export const INTENTS = {
  NAVIGATE_HOME: "NAVIGATE_HOME",
  NAVIGATE_LESSONS: "NAVIGATE_LESSONS",
  NAVIGATE_QUIZ: "NAVIGATE_QUIZ",
  NAVIGATE_DASHBOARD: "NAVIGATE_DASHBOARD",
  OPEN_LESSON: "OPEN_LESSON",
  NEXT_LESSON: "NEXT_LESSON",
  PREVIOUS_LESSON: "PREVIOUS_LESSON",
  START_QUIZ: "START_QUIZ",
  READ_LESSON: "READ_LESSON",
  STOP_READING: "STOP_READING",
  ASK_TUTOR: "ASK_TUTOR",
  SUBMIT_CODE: "SUBMIT_CODE",
  EVALUATE_PROGRESS: "EVALUATE_PROGRESS",
  LOGOUT: "LOGOUT",
  HELP: "HELP",
  REPEAT_LAST: "REPEAT_LAST",
};
